### ISSUE TITLE
help: `code group` and `details` will not be expanded

### ISSUE THREAD

**Issue by jinzhongjia** [condorheroblog/vitepress-export-pdf#26]
代码组网页交互逻辑是通过按钮切换查看的，到了 pdf 中就不行了，这个该如何处理呢

![image](https://github.com/user-attachments/assets/be4eef8f-e920-414e-a27e-f440321dee59)

datails 这种默认是折叠的在 pdf 中也是无法查看的：

![image](https://github.com/user-attachments/assets/a468a7da-cf14-4c2b-92d9-9371d17b2829)

能否可以通过某种hook的方法展开 defails ，让 code-group 在 pdf 直接一起渲染出来

**Comment by condorheroblog** [comment]
你可以这样做：

```html
window.addEventListener('beforeprint', function() {
  document.querySelectorAll('details').forEach(function(details) {
    details.setAttribute('open', '');
  });
});

window.addEventListener('afterprint', function() {
  document.querySelectorAll('details').forEach(function(details) {
    details.removeAttribute('open');
  });
});
```

**Comment by jinzhongjia** [comment]
额外补充一点：

关于代码块组可以选择覆盖默认的css或者使用js复制dom元素

代码块组的css ：https://github.com/vuejs/vitepress/blob/main/src/client/theme-default/styles/components/vp-code-group.css

我的选择是将tabs 隐藏，然后让代码块组完全显示

```css
@media print {
	.vp-code-group .tabs {
		display: none !important;
	}
	.vp-code-group div[class*="language-"],
	.vp-block {
		display: block !important;
		margin-top: 0 !important;
		border-top-left-radius: 0 !important;
		border-top-right-radius: 0 !important;
	}
}

```
